/obj/item/device/assembly/signaler/New()
	..()
	ADD_SAVED_VAR(code)
	ADD_SAVED_VAR(frequency)
	ADD_SAVED_VAR(delay)
	ADD_SAVED_VAR(airlock_wire)
	ADD_SAVED_VAR(deadman)

/obj/item/device/assembly/signaler/Initialize()
	. = ..()
	set_frequency(frequency)