/datum/reagent/dylovene/affect_blood(var/mob/living/carbon/M, var/alien, var/removed)
	if(alien == IS_PHOROSIAN)
		M.adjustBruteLoss(removed * 6)
	. = ..()
/datum/reagent/dexalin/affect_blood(var/mob/living/carbon/M, var/alien, var/removed)
	if(alien == IS_PHOROSIAN)
		M.adjustFireLoss(removed * 6)
	. = ..()
/datum/reagent/dexalinp/affect_blood(var/mob/living/carbon/M, var/alien, var/removed)
	if(alien == IS_PHOROSIAN)
		M.adjustFireLoss(removed * 9)
	. = ..()
/datum/reagent/oxygen/affect_blood(var/mob/living/carbon/M, var/alien, var/removed)
	if(alien == IS_PHOROSIAN)
		M.adjustToxLoss(removed * 6)
	. = ..()
/datum/reagent/toxin/phoron/affect_blood(var/mob/living/carbon/M, var/alien, var/removed)
	if(alien == IS_PHOROSIAN ) //pure phoron helps them regain blood, since it's a staple in their blood. Also promotes healing.
		M.add_chemical_effect(CE_BLOODRESTORE, 8 * removed)
		M.heal_organ_damage(3 * removed, 3 * removed)
	. = ..()
/datum/reagent/toxin/phoron/affect_touch(var/mob/living/carbon/M, var/alien, var/removed)
	if(alien != IS_PHOROSIAN)
		. = ..()
	return
