/datum/computer_file/New(var/list/md = null)
	..()
	ADD_SAVED_VAR(filename)
	ADD_SAVED_VAR(filetype)
	ADD_SAVED_VAR(size)
	ADD_SAVED_VAR(holder)
	ADD_SAVED_VAR(unsendable)
	ADD_SAVED_VAR(undeletable)
	ADD_SAVED_VAR(uid)
	ADD_SAVED_VAR(metadata)
	ADD_SAVED_VAR(papertype)