/mob/living/bot/farmbot/New(var/newloc, var/newTank)
	..(newloc)
	ADD_SAVED_VAR(waters_trays)
	ADD_SAVED_VAR(refills_water)
	ADD_SAVED_VAR(uproots_weeds)
	ADD_SAVED_VAR(replaces_nutriment)
	ADD_SAVED_VAR(collects_produce)
	ADD_SAVED_VAR(removes_dead)
	ADD_SAVED_VAR(tank)
