/decl/hierarchy/skill/medical/virology
	ID = "virology"
	name = "Virology"
	desc = "This skill implies an understanding of microorganisms and their effects on humans."
	levels = list( "Unskilled"			= "You know that diseases are contagious; you've probably heard you should wash your hands to stop their spread. You know that if you're sick, you can go to Medical and get treatment.",
						"Basic"				= "You know how viruses work, and you can use the machinery in the virology lab to analyze a virus or create an antibody. You know the principles of quarantine and you know how to keep a virus from spreading. You know that spaceacillin will help the body fight off a virus. However, you're not specialized in virology, and you probably don't have a whole lot of experience in dealing with viruses. If you are a medical doctor, you know how to treat symptoms and keep sick patients stable.<br>- You can read virus reports more or less precisely. This increases with level.",
						"Trained"			= "You know the full process of creating antibodies for a viral strain. You will generally be able to contain an infection and see that it is treated quickly.<br>- You can safely use the Disease Splicer and the Pathogenic Incubator.",
						"Experienced"		= "You know how to analyze, modify, and cure viruses, and could probably do so even without most of the equipment in the virology lab. You know how to trigger mutations in a virus and how to isolate genes. If you really wanted to, you could create a deadly virus, provided you got lucky with the mutations.<br>- You can fully operate the Disease Analyser.<br>- You can fully read virus reports.<br>- You can splice and mutate viruses more or less precisely.",
						"Master"		= "You are a specialized virologist - either a medical doctor or a scientific researcher. You may be well-known in the field, having published in prestigious journals; or you may be a mad scientist working away in secret. You know how to use a virus as a tool or a weapon. You can cure any epidemic and if you wanted to, you could start one so deadly and contagious that your targets wouldn't know what hit them.<br>- You can splice and mutate viruses precisely.")
	prerequisites = list(SKILL_MEDICAL = SKILL_ADEPT)
